n = int(input('Digite um numero: '))
print('A TABUADA DO NUMEOR DIGITADO SERA: ')
print(' 1x{}={:2}'.format(n, n*1))
print(' 2x{}={:2}'.format(n, n*2))
print(' 3x{}={:2}'.format(n, n*3))
print(' 4x{}={:2}'.format(n, n*4))
print(' 5x{}={:2}'.format(n, n*5))
print(' 6x{}={:2}'.format(n, n*6))
print(' 7x{}={:2}'.format(n, n*7))
print(' 8x{}={:2}'.format(n, n*8))
print(' 9x{}={:2}'.format(n, n*9))
print('10x{}={:2}'.format(n, n*10))
print('-'*12)
