#nome = int(input('Digite seu nome completo: ')).strip()
nome = input('Digite seu nome completo: ')
nome = nome.strip()
print(nome.upper())
print('---')
print(nome.lower())
print('-'*3)
print('O total de letras sem contar espaços sera: {}'.format(len(nome) - nome.count(' ')))
print('-'*3)
#print('seu primeiro nome tem {} letras'.format(len(nome)-nome.count(' ')))
nome = nome.split()
print('A quantidade de letras do primeiro nome sera: {}'.format(len(nome[0])))
